from abc import ABC, abstractmethod
from typing import Optional

from domain.entities.user.user_enty import UserEntity, UserEntityUpdated


class UserRepository(ABC):
    @abstractmethod
    async def find_by_id(self, user_id: str) -> Optional[UserEntity] | None:...
    @abstractmethod
    async def create(self, user: UserEntity) -> UserEntity:...
    @abstractmethod
    async def update(self, user: UserEntity) -> UserEntity:...
    @abstractmethod
    async def delete(self, user_id: str) -> UserEntity:...
    @abstractmethod
    async def get_all(self) -> list[UserEntity]:...
    @abstractmethod
    async def find_by_email(self, email: str) -> Optional[UserEntity] | None:...

    @abstractmethod
    async def find_all_by_team_id(self, team_id: str) -> list[UserEntityUpdated] | None:...