from abc import ABC


class RedisRepository(ABC):
    def connect(self) -> None:...
    def disconnect(self) -> None:...
    def set(self, key: str, value: any, ttl: int | None = None) -> bool:...
    def get(self, key: str, default: any = None) -> any:...
    def delete(self, *keys: str) -> int:...
    def exists(self, key: str) -> bool:...