from abc import ABC
from typing import Optional
from uuid import UUID

from domain.entities.role.role_entity import RoleEntity


class RoleRepository(ABC):
   async def find_by_id(self, role_id: UUID) -> Optional[RoleEntity] | None:...

   async def create(self, role: RoleEntity) -> RoleEntity:...

   async def update(self, role: RoleEntity) -> RoleEntity:...

   async def delete(self, role_id: UUID) -> RoleEntity:...

   async def get_all(self) -> list[RoleEntity]:...
   async def get_all_by_team(self, team_id: UUID) -> list[RoleEntity]:...

   async def find_by_name(self, name: str) -> Optional[RoleEntity] | None:...